# Generated by Django 3.0.6 on 2020-06-08 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_itdude', '0002_auto_20200607_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
