# Generated by Django 3.0.6 on 2020-06-10 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import send_itdude.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_itdude', '0003_auto_20200609_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='uploaded_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploaded_files',
            name='uploadedfile',
            field=models.FileField(upload_to='', validators=[send_itdude.validators.validate_file_size]),
        ),
    ]
